apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: runner
          image: myoung34/github-runner:ubuntu-dind
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: REPO_URL
              valueFrom:
                secretKeyRef:
                  name: github-runner
                  key: REPO_URL
            - name: RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner
                  key: RUNNER_TOKEN
            - name: RUNNER_NAME
              value: k8s-dind-runner
            - name: RUNNER_GROUP
              value: default
            - name: RUNNER_WORKDIR
              value: _work
            - name: ORG_RUNNER
              value: 'false'
          volumeMounts:
            - name: work
              mountPath: /runner/_work
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: work
          emptyDir: {}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
