name: Deploy FastAPI para o cluster local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verificar kubectl
        run: kubectl version --client

      - name: Aplicar YAML do FastAPI
        run: kubectl apply -f k8s/fastapi.yaml
