name: Build and Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest

      - name: Set image on Kubernetes
        run: |
          kubectl set image deployment/fastapi-app fastapi=ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest --record || \
          kubectl apply -f k8s/fastapi.yaml
