name: Build and Deploy FastAPI with Kaniko

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build and push Docker image with Kaniko
        uses: addnab/docker-run-action@v3
        with:
          image: gcr.io/kaniko-project/executor:latest
          options: >
            -v ${{ github.workspace }}:/workspace
          run: |
            /kaniko/executor \
              --context /workspace \
              --dockerfile /workspace/Dockerfile \
              --destination ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest \
              --skip-tls-verify \
              --verbosity debug
