name: Build and Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    container:
      image: gcr.io/kaniko-project/executor:latest
      options: --entrypoint="" # remove o entrypoint default
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image with Kaniko
        run: |
          /kaniko/executor \
            --context . \
            --dockerfile Dockerfile \
            --destination ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest \
            --insecure \
            --skip-tls-verify \
            --verbosity debug \
            --log-timestamp
