name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build da imagem
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest .

      - name: Push da imagem
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-minimal:latest
