name: Build e Push para Docker Hub + Deploy no Cluster

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-minimal:latest .

      - name: Push para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-minimal:latest

      - name: Aplicar manifest no cluster
        run: |
          kubectl apply -f k8s/fastapi.yaml
