name: Runner Local - FastAPI Minimal

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    name: Testar runner no cluster local
    runs-on: [self-hosted, linux]
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Exibir ambiente do runner
        run: |
          echo "Hostname: $(hostname)"
          echo "Data/hora: $(date)"
          echo "Branch: ${{ github.ref }}"

      - name: Verificar Python
        run: python3 --version

      - name: Verificar estrutura do app
        run: |
          ls -lah
          cat main.py || echo "main.py não encontrado"

      - name: Simular deploy no Kubernetes (sem efeito real)
        run: |
          echo "kubectl apply -f k8s/fastapi.yaml"
